generations:
  max: 100000
population:
  size: 250
  limit: 100
fitness:
  algorithm: 'sumDifference'
mating:
  algorithm: 'randomPick'
crossover:
  algorithm: 'singlePointMiddle'
mutation:
  chance: 0.05
  algorithm: 'singleCharacter'